site: Ryan Wentzel

url: https://ryanlwentzel.com
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  projects:
    output: false
    permalink: /project/:slug
  essays:
    output: true
    permalink: /essays/:slug/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "articles"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "essays"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - github-pages, group: :jekyll_plugins

paginate: 6
paginate_path: "page/:num"
  