exclude:
    - vendor

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Ryan Wentzel
tagline:          "The blog"
description:      "The online home of Ryan Wentzel"
url:              http://ryanlwentzel.com
baseurl:
domain:           ryanlwentzel.com
timezone:         America/Los_Angeles
paginate:         5
paginate_path:  page/:num
rss_url:		  "http://feeds.feedburner.com/ryanlwentzel/feed"
assets_path:	  /public
cdn_url:          https://d1yo597syf8yny.cloudfront.net
home_page:        index.html
home_page_inc:    /

author:
  name:           'Ryan Wentzel'
  url:            https://twitter.com/ryanwentzel
  twitter:        "http://twitter.com/ryanwentzel"
  twitter_handle: "ryanwentzel"
  github:         "https://github.com/ryanwentzel"
  google_plus:    "https://plus.google.com/102403255229684786847"
  flickr:         "https://www.flickr.com/photos/rwentzel/"


keywords: 		  "Christianity, gospel, church, Reformed Baptist, Escondido, Christian books"

# social


# navbar

pages_list: { "About": "/about/", "Contact": "/contact/" }

plugins:
    - jekyll-sitemap
    - jekyll-redirect-from
    - github-pages, group: :jekyll_plugins

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
