basic_settings:
  site_title: Ryan Wentzel
  site_tagline: δοῦλος Ἰησοῦ Χριστοῦ
  site_vocation: "δοῦλος Ἰησοῦ Χριστοῦ"
  site_author: Ryan Wentzel 
  site_email: hi@ryanlwentzel.com
  favicon_image: /favicon.ico
  header_image: https://d1yo597syf8yny.cloudfront.net/images/theme/forest-pond-crop.jpg

cdn:
  url: https://d1yo597syf8yny.cloudfront.net
  journal_js_url: https://d1yo597syf8yny.cloudfront.net/js/journal-min.js
  jquery_url: https://d1yo597syf8yny.cloudfront.net/js/libs/jquery/3.2.1/jquery.min.js

header_settings:
  logo_image: 
  logo_width: 200
  overlay_opacity: 0.5

menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about'
    - title: 'Resources'
      url: '/resources'
    - title: 'Subscribe'
      url: '/subscribe'
    - title: 'Contact'
      url: '/contact'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: 'https://www.instagram.com/ryanwentzel/'
  snapchat_url: ''
  youtube_url: 'https://www.youtube.com/channel/UChDSSOO_z11aGFaFKVCbGlg'
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#FFFFFF'
  background_alt_color: '#F5F7FA'
  text_dark_color: '#0061C9'
  text_medium_color: '#231f20'
  text_light_color: '#ABB7B7'
  accent_color: '#0061C9'
  border_color: '#dddddd'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;1,300;1,700&family=Montserrat:wght@300;400;600;700&display=swap" rel="stylesheet">
  title_font: '"Montserrat", Helvetica, Arial, sans-serif'
  body_font: '"Merriweather", Georgia, serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 400
    letter_spacing: 0
  site_tagline:
    small_size: 13
    medium_size: 13
    large_size: 16
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 30
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 30
    medium_size: 35
    large_size: 38
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 25
    medium_size: 30
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 20
    medium_size: 25
    large_size: 25
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 17
    large_size: 17
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 15
    medium_size: 15
    large_size: 15
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 18
    large_size: 18
    weight: 400
    letter_spacing: 0
    line_height: 1.8
  blockquote:
    small_size: 16
    medium_size: 16
    large_size: 18
    weight: 400
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: false
  analytics_code: "<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51416-7', 'ryanlwentzel.com');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

</script>"