#!/bin/bash

cdn_base="https://cdn.ryanlwentzel.com"
cdn_photos="$cdn_base/assets/img/photos/"
cdn="https://cdn.ryanlwentzel.com/assets/img/content/"
collections_dir="$project_dir/collections"
podcasts_dir="$collections_dir/_sermons"

# create article
function article () {
    local title="${1}"
    local subtitle="${2}"
    local title_lower=$(echo $title | tr '[:upper:]' '[:lower:]')
    local suffix="${title_lower// /-}"
    local date=$(date +"%Y-%m-%d")
    local slug="$date-$suffix"
    local articles_dir="$collections_dir/_articles"
    local filename="$articles_dir/$slug.md"
    echo "Creating $filename"
    cat << DELIMIT > "$filename"
---
title: $title
subtitle: $subtitle
description: 
date: $(date +'%Y-%m-%d %H:%M:%S %z')
img: 
    url: $cdn
    alt:
published: false 
---


DELIMIT

code "$filename"
}

# create newsletter
function newsletter () {
    local title="${1}"
    local subtitle="${2}"
    local title_lower=$(echo $title | tr '[:upper:]' '[:lower:]')
    local suffix="${title_lower// /-}"
    local date=$(date +"%Y-%m-%d")
    local slug="$date-$suffix"
    local newsletter_dir="$collections_dir/_newsletter"
    local filename="$newsletter_dir/$slug.md"
    echo "Creating $filename"
    cat << DELIMIT > "$filename"
---
title: $title
subtitle: $subtitle
description: 
date: $(date +'%Y-%m-%d %H:%M:%S %z')
img: 
    url: $cdn
published: false 
---

## A Prayer Based on <INSERT REF>

{% include newsletter/sections/prayer.html path="_prayers/2024-05-07-incomparable-beauty-and-splendor.md" %}

[Read more prayers I've written]({{ site.data.nav.prayers | absolute_url }} "Read prayers written by Ryan Wentzel")

## Talks

![Old German Bible opened to the Psalms resting on top of a rustic wooden table](https://cdn.ryanlwentzel.com/assets/img/content/herrmann-stamm-19iL-6uC5C4-unsplash-md.webp)

- [Item](#)
- [Item](#)
- [Item](#)

## Art I'm Enjoying

<figure>
    <img class="img-fluid rounded-2" src="https://cdn.ryanlwentzel.com/assets/img/content/edward_mitchell_bannister-streamside-1870-newsletter.webp" alt="Landscape painting by Edward Mitchell Bannister" />
    <figcaption>
        Edward Mitchell Bannister, <em>Streamside</em>, 1870
    </figcaption>
</figure>

## Poetry I'm Enjoying

## Quote of the Moment

> Insert quote here.

— Insert source here.

[Explore other quotes I've collected]({{ site.data.nav.commonplace | absolute_url }} "Browse a collection of quotes and excerpts from Ryan Wentzel's reading")

{% include newsletter/sections/footer.html -%}

DELIMIT

code "$filename"

}

# Create a new podcast episode
function podcast () {
    local title="${1}"
    local subtitle="${2}"
    local title_lower=$(echo $title | tr '[:upper:]' '[:lower:]')
    local suffix="${title_lower// /-}"
    local date=$(date +"%Y-%m-%d")
    local slug="$date-$suffix"
    local filename="$podcasts_dir/$slug.md"
    echo "Creating $filename"
    cat << DELIMIT > "$filename"
---
title: $title
subtitle: $subtitle
description: 
date: $(date +'%Y-%m-%d %H:%M:%S %z')
published: false
img:
    alt: ""
    url: "$cdn"
    url_md: "$cdn"
    url_sm: "$cdn"
episode_id: 
---

DELIMIT

code "$filename"

}

# Create a new prayer
function prayer () {
    local title="${1}"
    local subtitle="${2}"
    local title_lower=$(echo $title | tr '[:upper:]' '[:lower:]')
    local suffix="${title_lower// /-}"
    local date=$(date +"%Y-%m-%d")
    local slug="$date-$suffix"
    local prayers_dir="$collections_dir/_prayers"
    local filename="$prayers_dir/$slug.md"
    echo "Creating $filename"
    cat << DELIMIT > "$filename"
---
title: $title
subtitle: $subtitle
description: 
date: $(date +'%Y-%m-%d %H:%M:%S %z')
published: false
img:
    url: $cdn
    alt:
series:
---

DELIMIT

code "$filename"

}

# create commonplace entry
function commonplace () {
    local title="${1}"
    local subtitle="${2}"
    local title_lower=$(echo $title | tr '[:upper:]' '[:lower:]')
    local suffix="${title_lower// /-}"
    local date=$(date +"%Y-%m-%d")
    local slug="$date-$suffix"
    local commonplace_dir="$collections_dir/_commonplace"
    local filename="$commonplace_dir/$slug.md"
    echo "Creating $filename"
    cat << DELIMIT > "$filename"
---
title: $title
subtitle: $subtitle
description: 
date: $(date +'%Y-%m-%d %H:%M:%S %z')
img:
    url_lg: "$cdn_base/assets/img/content/"
    url_md: "$cdn_base/assets/img/content/"
    url_sm: "$cdn_base/assets/img/content/"
    alt: ""
published: false 
---

DELIMIT

code "$filename"

}

# create photo entry
function photo () {
    local title="${1}"
    local subtitle="${2}"
    local title_lower=$(echo $title | tr '[:upper:]' '[:lower:]')
    local suffix="${title_lower// /-}"
    local date=$(date +"%Y-%m-%d")
    local slug="$date-$suffix"
    local dest_dir="$collections_dir/_photos"
    local filename="$dest_dir/$slug.md"
    echo "Creating $filename"
    cat << DELIMIT > "$filename"
---
title: $title
seo_title: 
subtitle: $subtitle
description: 
seo_description: 
date: $(date +'%Y-%m-%d %H:%M:%S %z')
img:
    url: "$cdn_photos"
    alt: ""
    url_sm: "$cdn_photos"
    caption:
    shutter_speed:
    aperture:
    iso:
    lens: 50 mm (EFS50mm f/1.4 USM)
    camera: Canon EOS 6D
    date:
    location: Escondido, California
published: false 
---

DELIMIT

code "$filename"

}

# create resource entry
function resource () {
    local title="${1}"
    local subtitle="${2}"
    local title_lower=$(echo $title | tr '[:upper:]' '[:lower:]')
    local suffix="${title_lower// /-}"
    local date=$(date +"%Y-%m-%d")
    local slug="$date-$suffix"
    local resource_dir="$collections_dir/_resources"
    local filename="$resource_dir/$slug.md"
    echo "Creating $filename"
    cat << DELIMIT > "$filename"
---
seo_title: 
title: $title
subtitle: $subtitle
description: 
seo_description: 
date: $(date +'%Y-%m-%d %H:%M:%S %z')
img:
    url: "$cdn"
    alt: ""
    url_md: "$cdn"
    url_sm: "$cdn"
published: false 
---

DELIMIT

code "$filename"

}
